Repository dhall-mock/dhall-mock, pull requests merged in 2020-04, with the labels that each got.

#13 Add github action on PR
  .github/workflows/pr.yml
Labels: rockstar automerge

#15 feat: Add github templates for issues and pullrequests
  .github/ISSUE_TEMPLATE/0.0.1-milestone.md
  .github/pull_request_template.md
Labels: rockstar automerge

#10 feat: Add error library and examples for error management
  Cargo.lock
  Cargo.toml
  examples/errors/main.rs
  src/main.rs
Labels: needs review

#12 feat: #3 integration dhall model for expectation in rust
  src/expectation/mod.rs
  src/expectation/model.rs
  src/main.rs
Labels: needs review

#18 Feat/4 add error library
  Cargo.lock
  Cargo.toml
  examples/logger.rs
  src/main.rs
Labels: rockstar automerge

#26 Web server integration
  Cargo.lock
  Cargo.toml
  dhall/Mock/package.dhall
  dhall/static.dhall
  src/expectation/model.rs
  src/main.rs
  src/web.rs
Labels: needs review

#27 Add cli for program
  Cargo.lock
  Cargo.toml
  dhall/static2.dhall
  src/cli.rs
  src/main.rs
Labels: loc:small, needs review

#31 feat: add github action on master for building
  .github/workflows/master.yml
Labels: rockstar automerge

#35 Configure configuration laod to be executed in separate runtime
  dhall/error.dhall
  dhall/example.dhall
  src/expectation/model.rs
  src/main.rs
Labels: needs review

#39 Add graceful shutdown for webserver
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  src/lib.rs
  src/web.rs
Labels: needs review

#41 Add admin server endpoint
  .github/workflows/pr.yml
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  src/cli.rs
  src/expectation/model.rs
  src/lib.rs
  src/web.rs
  tests/api_tests.rs
Labels: needs review

#45 Use dhal mock type through github instead of local binding
  dhall/error.dhall
  dhall/example.dhall
  dhall/static.dhall
Labels: needs review

#43 Fix : Error on web server should crash appliation with informations
  src/bin/main.rs
  src/lib.rs
Labels: needs review, rockstar automerge

#50 Admin: Compile and integrate dhall configuration on POST /expectations
  src/bin/main.rs
  src/expectation/model.rs
  src/lib.rs
  src/web.rs
  tests/api_tests.rs
Labels: needs review

#54 Refacto: Modify projects code structure (clean / reorganize)
  src/bin/main.rs
  src/cli.rs
  src/expectation/mod.rs
  src/lib.rs
  src/mock/compilation.rs
  src/mock/mod.rs
  src/mock/model.rs
  src/mock/service.rs
  src/web.rs
  src/web/admin.rs
  src/web/mock.rs
  src/web/mod.rs
  tests/api_tests.rs
Labels: needs review

#60 Generate port randomly for integration tests
  .github/workflows/pr.yml
  src/lib.rs
  tests/api_tests.rs
Labels: needs review
